// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKDNVhiLLlCQwdUKJyfy79popzuDtQNiA',
    appId: '1:414572143893:web:eda2cbf69480eaec1c351c',
    messagingSenderId: '414572143893',
    projectId: 'rpifirebase-8e8b1',
    authDomain: 'rpifirebase-8e8b1.firebaseapp.com',
    storageBucket: 'rpifirebase-8e8b1.appspot.com',
    measurementId: 'G-FGBTRWCBPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZB533U7g80O9AXX_vmQt6YieV3mfPVSc',
    appId: '1:414572143893:android:b8ad96b03f41c8421c351c',
    messagingSenderId: '414572143893',
    projectId: 'rpifirebase-8e8b1',
    storageBucket: 'rpifirebase-8e8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyv9xtTXN_AiJz-SrR4tJOCz2zgI8nJDA',
    appId: '1:414572143893:ios:33f1992346722b401c351c',
    messagingSenderId: '414572143893',
    projectId: 'rpifirebase-8e8b1',
    storageBucket: 'rpifirebase-8e8b1.appspot.com',
    iosBundleId: 'com.example.ecorevs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyv9xtTXN_AiJz-SrR4tJOCz2zgI8nJDA',
    appId: '1:414572143893:ios:526cdd3045a7596e1c351c',
    messagingSenderId: '414572143893',
    projectId: 'rpifirebase-8e8b1',
    storageBucket: 'rpifirebase-8e8b1.appspot.com',
    iosBundleId: 'com.example.ecorevs.RunnerTests',
  );
}
